applications:
- application_name: JitDev
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://platform.dev.jitdev.io
  type: web
aws:
- account_id: '452808376969'
  regions:
  - us-east-1
  type: org
